inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'test/**/*'
    - 'lib/fhir_models/fhir/**/*'
    - 'lib/fhir_models/fluentpath/evaluate.rb'
    - 'tmp/**/*'
    - '*.gemspec'
    - 'bin/*'
Metrics/LineLength:
  Enabled: false
