inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'lib/fhir_stu3_models/fhir/**/*'
    - 'lib/fhir_stu3_models/fluentpath/evaluate.rb'
    - 'lib/**/*.rake'
    - 'tmp/**/*'
    - '*.gemspec'
    - 'bin/*'
Metrics/LineLength:
  Enabled: false
inherit_mode:
  merge:
    - Exclude
