language: ruby
rvm:
  - "2.0.0"
  - "2.1.10"
  - "2.2.5"
  - "2.3.1"
script:
  - bundle exec rake test
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change
addons:
    code_climate:
        repo_token: 0230b3379581b30743b7b4355d7394e427648e604d19a2aba987956201eee290
