language: ruby
rvm:
  - "2.0.0"
script:
  - bundle exec rake fhir:generate 
  - bundle exec rake test
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change
